//
//  CurrencyModels.swift
//  TesteiOSv2-VitorNeves
//
//  Created by joao.vitor.f.naves on 04/03/2019.
//  Copyright (c) 2019 joao.vitor.f.naves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class Currency {
    
    struct Request {
        var userId: Int? = 0
    }
    
    struct Response : Codable {
        var statementList: [Statement]?
        var error: ErrorRepo?
    }
    
    struct Statement: Codable {
        var title: String?
        var desc: String?
        var date: String?
        var value: Double?
    }
}
