//
//  CurrencyRouter.swift
//  TesteiOSv2-VitorNeves
//
//  Created by joao.vitor.f.naves on 04/03/2019.
//  Copyright (c) 2019 joao.vitor.f.naves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CurrencyRoutingLogic
{
    func goToLogin()
}

protocol CurrencyDataPassing
{
    var dataStore: CurrencyDataStore? { get }
}

class CurrencyRouter: NSObject, CurrencyRoutingLogic, CurrencyDataPassing
{
    weak var viewController: CurrencyViewController?
    var dataStore: CurrencyDataStore?
    let mainStoryBoard = UIStoryboard(name: "Main", bundle: Bundle.main)
    
    // MARK: - Routing
    
    func goToLogin() {
        guard let view = mainStoryBoard.instantiateViewController(withIdentifier: "LocationViewController") as? LocationViewController else {
            print("saiu")
            return
        }
        view.modalTransitionStyle = .coverVertical
        viewController?.present(view, animated: true, completion: nil)
    }
}
