//
//  CurrencyWorker.swift
//  TesteiOSv2-VitorNeves
//
//  Created by joao.vitor.f.naves on 04/03/2019.
//  Copyright (c) 2019 joao.vitor.f.naves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

//MARK: - Typealias
typealias completionStatement = (Currency.Response?) -> Void
typealias failure = (Error) -> Void

class CurrencyWorker
{
    
    //MARK: - Get Statements
    func fetchStatements(userId:Int!, completion: @escaping(completionStatement), failure: @escaping failure) {
        RequestManager.shared.get("\(APISession.APIEndPoint)/statements/\(userId ?? 0)", model: Currency.Response.self, completion: { (statementResponse) in
            if statementResponse?.error?.code == nil{
                completion(statementResponse)
            }else{
                completion(nil)
            }
        }) { (error) in
            failure(error)
        }
    }
}
