//
//  CurrencyModels.swift
//  TesteiOSv2-VitorNeves
//
//  Created by joao.vitor.f.naves on 04/03/2019.
//  Copyright (c) 2019 joao.vitor.f.naves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class Currency {
    
    struct Request {
        var userId = 0
    }
    
    struct Response : Codable {
        var statementList: [Statement]?
        var error: ErrorRepo?
    }
    //Model
    struct Statement: Codable {
        var title: String?
        var desc: String?
        var date: String?
        var value: Double?
    }
//    struct Statement: Mappable {
//        let title: String
//        let desc: String
//        let date: Date
//        let value: Float64
//
//        init(_ map: [String : Any]) {
//            self.title = map.property("title")!
//            self.desc = map.property("desc")!
//            self.date =  map.transform("date", transformer: { (value: String) -> Date? in
//                let df = DateFormatter()
//                df.dateFormat = "yyyy-MM-dd"
//                return df.date(from: value)!
//            })!
//            self.value = map.property("value")!
//        }
//    }
}


