//
//  CurrencyInteractor.swift
//  TesteiOSv2-VitorNeves
//
//  Created by joao.vitor.f.naves on 04/03/2019.
//  Copyright (c) 2019 joao.vitor.f.naves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

//MARK: - Protocols
protocol CurrencyBusinessLogic
{
    func getUserAccount() -> Location.UserAccount?
    func fetchStatements(request: Currency.Request)
}

protocol CurrencyDataStore
{
    var userAccount: Location.UserAccount? { get set }
}

class CurrencyInteractor: CurrencyBusinessLogic, CurrencyDataStore
{
    
    //MARK: - Properties
    var presenter: CurrencyPresentationLogic?
    var worker: CurrencyWorker?
    var userAccount: Location.UserAccount?
    
    //MARK: - Actions
    func getUserAccount() -> Location.UserAccount? {
        return userAccount
    }
    
    func fetchStatements(request: Currency.Request) {
        worker = CurrencyWorker()
        worker?.fetchStatements(userId: request.userId, completion: { (responseStatements) in
            guard let responseStatements = responseStatements else{
                return
            }
            self.presenter?.presentStatements(response: responseStatements, error: nil)
        }, failure: { (error) in
            print(error.localizedDescription)
            self.presenter?.presentStatements(response: nil, error: error)
        })
    }
}
