//
//  LocationWorker.swift
//  TesteiOSv2-VitorNeves
//
//  Created by joao.vitor.f.naves on 04/03/2019.
//  Copyright (c) 2019 joao.vitor.f.naves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

//MARK: - typealias
typealias completionLogin = (Location.Login.Response?) ->Void
//typealias failure = (Error) -> Void

class LocationWorker
{
    func login(user:String!, password:String!, completion:@escaping(completionLogin), failure: @escaping(failure)) {
        
        let parameters: Parameters = [
        "user": user,
        "password": password
        ]
        
        RequestManager.shared.post("\(APISession.APIEndPoint)/login", model: Location.Login.Response.self, params: parameters, completion: { (loginResponse) in
            print(loginResponse)
            completion(loginResponse)
        }) { (error) in
            print(error.localizedDescription)
            failure(error)
        }
    }
}
