//
//  LocationPresenter.swift
//  TesteiOSv2-VitorNeves
//
//  Created by joao.vitor.f.naves on 04/03/2019.
//  Copyright (c) 2019 joao.vitor.f.naves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

//MARK: - Protocols
protocol LocationPresentationLogic
{
    func presentLoginResults(response: Location.Login.Response?, error: Error?)
}

class LocationPresenter: LocationPresentationLogic
{
    //MARK: - Properties
    weak var viewController: LocationDisplayLogic?
  
    //MARK: - Actions
    func presentLoginResults(response: Location.Login.Response?, error: Error?)
    {
        if response?.userAccount != nil {
            guard let userAccount = response?.userAccount else{
                return
            }
            viewController?.validLogin(userAccount)
        } else {
            viewController?.displayError(response?.error)
        }
    }
}
