//
//  LocationRouter.swift
//  TesteiOSv2-VitorNeves
//
//  Created by joao.vitor.f.naves on 04/03/2019.
//  Copyright (c) 2019 joao.vitor.f.naves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

//MARK: - Protocols

protocol LocationRoutingLogic
{
    func goToCurrency(userAccount: Location.UserAccount)
}

protocol LocationDataPassing
{
    var dataStore: LocationDataStore? { get }
}

class LocationRouter: NSObject, LocationRoutingLogic, LocationDataPassing
{
    //MARK: - Properties
    
    weak var viewController: LocationViewController?
    var dataStore: LocationDataStore?
    let mainStoryBoard = UIStoryboard(name: "Main", bundle: Bundle.main)
    
    // MARK: - Routing
    
    func goToCurrency(userAccount: Location.UserAccount) {
        guard let destinationVC = mainStoryBoard.instantiateViewController(withIdentifier: "CurrencyViewController") as? CurrencyViewController else {
            return
        }
        var destinationDS = destinationVC.router!.dataStore!
        passDataToSomewhere(source: dataStore!, destination: &destinationDS)
        destinationVC.modalTransitionStyle = .flipHorizontal
        viewController?.present(destinationVC, animated: true, completion: nil)
    }
    
    func passDataToSomewhere(source: LocationDataStore, destination: inout CurrencyDataStore) {
        destination.userAccount = source.userAccount
    }
}
