//
//  LocationPresenter.swift
//  TesteiOSv2-VitorNeves
//
//  Created by joao.vitor.f.naves on 04/03/2019.
//  Copyright (c) 2019 joao.vitor.f.naves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LocationPresentationLogic
{
  func presentSomething(response: Location.Something.Response)
}

class LocationPresenter: LocationPresentationLogic
{
  weak var viewController: LocationDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Location.Something.Response)
  {
    let viewModel = Location.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
