//
//  LocationModels.swift
//  TesteiOSv2-VitorNeves
//
//  Created by joao.vitor.f.naves on 04/03/2019.
//  Copyright (c) 2019 joao.vitor.f.naves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct Location {
    
    struct Login {
        
        struct Request {
            var user: String?
            var password: String?
        }
        
        struct Response{
            var userAccount: UserAccount?
            var error: Error?
        }
        
    }
    
    class UserAccount : NSObject {
        var userId = 0
        var name: String = ""
        var bankAccount: String = ""
        var agency: String = ""
        var balance: Float64 = 0.0
        
        init(userId: Int, name: String, bankAccount: String, agency: String, balance: Float64) {
            self.userId = userId
            self.name = name
            self.bankAccount = bankAccount
            self.agency = agency
            self.balance = balance
        }
    }
    
    struct Error {
        var code: Int
        var message: String
    }
}
