//
//  LocationInteractor.swift
//  TesteiOSv2-VitorNeves
//
//  Created by joao.vitor.f.naves on 04/03/2019.
//  Copyright (c) 2019 joao.vitor.f.naves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

//MARK: - Protocols
protocol LocationBusinessLogic
{
    func postLogin(_ request: Location.Login.Request)
}

protocol LocationDataStore
{
    var userAccount: Location.UserAccount? { get set }
}

class LocationInteractor: LocationBusinessLogic, LocationDataStore
{
    //MARK: - Properties
    var presenter: LocationPresentationLogic?
    var worker: LocationWorker?
    var userAccount: Location.UserAccount?
    
    //MARK: - Actions
    func postLogin(_ request: Location.Login.Request) {
        worker = LocationWorker()
        worker?.postLogin(user: request.user!, password: request.password, completion: { (loginResponse) in
            self.userAccount = loginResponse?.userAccount
            self.presenter?.presentLoginResults(response: loginResponse, error: nil)
        }, failure: { (error) in
            self.presenter?.presentLoginResults(response: nil, error: error)
        })
    }
}
