//
//  LocationViewController.swift
//  TesteiOSv2-VitorNeves
//
//  Created by joao.vitor.f.naves on 04/03/2019.
//  Copyright (c) 2019 joao.vitor.f.naves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

//MARK: - Protocols
protocol LocationDisplayLogic: class
{
    func displayError(_ error: ErrorRepo?)
    func validLogin(_ userAccount: Location.UserAccount)
    func validateLogin() -> Bool
}

class LocationViewController: UIViewController, LocationDisplayLogic
{
    //MARK: - Outlets
    @IBOutlet weak var userField: UITextField!
    @IBOutlet weak var passwordField: UITextField!
    
    //MARK: - Properties
    var interactor: LocationBusinessLogic?
    var router: (NSObjectProtocol & LocationRoutingLogic & LocationDataPassing)?
    
    //MARK: - Lifecycle
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        self.userField.becomeFirstResponder()
    }

    //MARK: - Set View
    private func setup()
    {
        let viewController = self
        let interactor = LocationInteractor()
        let presenter = LocationPresenter()
        let router = LocationRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    //MARK: - Message
    func displayError(_ error: ErrorRepo?){
        self.dismissHUD()
        self.showAlert(title: "Bank", message: error?.message ?? "")
    }
    
    //MARK: - Validate
    func validLogin(_ userAccount: Location.UserAccount){
        self.dismissHUD()
        router?.goToCurrency(userAccount: userAccount)
    }
    
    func validateLogin() -> Bool{
        let user = self.userField.text!
        let password = self.passwordField.text!
        
        if user.isNumeric {
            if !user.isValidCPF(){
                self.showAlert(title: "Bank", message: "CPF informado é inválido.")
                return false
            }
            
        } else if !user.isValidEmail() {
            self.showAlert(title: "Bank", message: "Usuário informado é inválido.")
            return false
        }
        
        if !password.isValidPassword() {
            self.showAlert(title: "Bank", message: "Senha informada é inválida.")
            return false
        }
        
        return true
    }

    //MARK: - Actions
    @IBAction func loginAction(_ sender: UIButton) {
        if validateLogin() {
            self.showHUD()
            let request = Location.Login.Request(user: self.userField.text!, password: self.passwordField.text!)
            interactor?.postLogin(request)
        }
    }
}
