# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TesteiOSv2-VitorNeves' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TesteiOSv2-VitorNeves
    pod 'Alamofire', '~> 4.7'
    pod 'SVProgressHUD'

  target 'TesteiOSv2-VitorNevesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TesteiOSv2-VitorNevesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
